package com.ehospital.billdesk.billdeskdemo.enums;
public enum ErrorType {
    DUPLICATE_REQUEST_ERROR,
    INVALID_REQUEST_ERROR,
    AUTHENTICATION_ERROR,
    INACCESSIBLE_RESOURCE_ERROR,
    NOT_FOUND_ERROR,
    INVALID_METHOD_ERROR,
    INVALID_MEDIA_TYPE_ERROR,
    INVALID_DATA_ERROR,
    API_VALIDATION_ERROR,
    API_PROCESSING_ERROR,
    API_CONNECTION_ERROR
}
